[workspace]
resolver = "3"
members = ["hadal", "hadal-loaders", "hadal-viewer"]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

unwrap_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
dbg_macro = "warn"

print_stdout = "warn"
print_stderr = "warn"

std_instead_of_core = "warn"

allow_attributes = "warn"
allow_attributes_without_reason = "warn"

cast_possible_truncation = "allow"
cast_precision_loss = "allow"
